name: unison-codebase-sqlite
github: unisonweb/unison

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DeriveFunctor
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - PatternSynonyms
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies

library:
  source-dirs: .

extra-source-files:
  - sql/*

dependencies:
  - base
  - bytes
  - bytestring
  - containers
  - extra
  - here
  - lens
  - generic-lens
  - monad-validate
  - mtl
  - safe
  - sqlite-simple
  - text
  - transformers
  - unliftio
  - vector
  - unison-codebase
  - unison-codebase-sync
  - unison-core
  - unison-prelude
  - unison-util
  - unison-util-serialization
  - unison-util-term
