name: unison-util-term
github: unisonweb/unison

library:
  source-dirs: .
  when:
    - condition: false
      other-modules: Paths_unison_util_term

dependencies:
  - base
  - containers
  - mtl
  - unison-core
  - unison-codebase
