name: save stack cache
description: save ~/.stack and .stack-work caches on Linux, macOS, and Windows

inputs:
  cache-prefix:
    description: The cache prefix to use for `~/.stack`, e.g. "release" or "ci"
    required: true
  work-cache-prefix:
    description: The cache prefix to use for `**/.stack-work`, e.g. "release" or "ci"
    required: true
    default: ${{inputs.cache-prefix}}


runs:
  using: composite
  steps:
    - name: check .stack cache
      id: check-stack
      uses: actions/cache/restore@v4
      with:
        key: ${{inputs.cache-prefix}}-stack-${{runner.os}}_${{env.resolver}}-${{hashFiles('**/stack.yaml', '**/package.yaml')}}

    - name: check .stack-work cache
      id: check-stack-work
      uses: actions/cache/restore@v4
      with:
        key: ${{inputs.work-cache-prefix}}-stack-work-${{runner.os}}_${{env.resolver}}-${{hashFiles('**/stack.yaml', '**/package.yaml')}}-${{hashFiles('**/*.hs')}}

    - name: save ~/.stack (non-Windows)
      if: runner.os != 'Windows' && steps.check-stack.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/.stack
        key: ${{inputs.cache-prefix}}-stack_${{runner.os}}-${{env.resolver}}-${{hashFiles('**/stack.yaml', '**/package.yaml')}}

    - name: save ~/.stack (Windows)
      if: runner.os == 'Windows' && steps.check-stack.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          C:\Users\runneradmin\AppData\Roaming\stack
          C:\Users\runneradmin\AppData\Local\Programs\stack
        key: ${{inputs.cache-prefix}}-stack_${{runner.os}}-${{env.resolver}}-${{hashFiles('**/stack.yaml', '**/package.yaml')}}

    - name: save .stack-work
      uses: actions/cache/save@v4
      with:
        path: |
          **/.stack-work
        key: ${{inputs.work-cache-prefix}}-stack-work_${{runner.os}}-${{env.resolver}}-${{hashFiles('**/stack.yaml', '**/package.yaml')}}-${{hashFiles('**/*.hs')}}
