name: ormolu

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

env:
  ormolu_version: "0.5.2.0"

jobs:
  ormolu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v15
        with:
          version: ${{ env.ormolu_version }}
          mode: inplace
      - name: create pull request with formatting changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit_message: automatically run ormolu
          branch: format/${{github.ref_name}}
          branch_suffix: random
          title: autoformat ${{github.ref_name}}
