name: ormolu

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

env:
  ormolu_version: "0.5.0.1"

jobs:
  ormolu:
    runs-on: ubuntu-20.04
    # Only run formatting on trunk commits
    # This is because the job won't have permission to push back to
    # contributor forks on contributor PRs.
    if: github.ref_name == 'trunk'
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v15
        with:
          version: ${{ env.ormolu_version }}
          mode: inplace
      - name: apply formatting changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit_message: automatically run ormolu
          branch_suffix: random
