name: pre-release
run-name: pre-release ${{inputs.version}}

defaults:
  run:
    shell: bash

on:
  workflow_run:
    workflows: ["CI"]
    branches: [trunk]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: specify the tag name for the release
        required: false

jobs:
  bundle-ucm:
    name: build and bundle ucm
    uses: ./.github/workflows/bundle-ucm.yaml
    with:
      ref: ${{ github.ref }}

  release:
    name: create release
    runs-on: ubuntu-20.04
    needs:
      - bundle-ucm

    steps:
      - name: make download dir
        run: mkdir /tmp/ucm

      - name: "download artifacts"
        uses: actions/download-artifact@v4
        with:
          path: /tmp/ucm

      - name: derive release tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            ref_name=${{ github.event.inputs.tag }}
          else
            ref_name=$(echo ${{ github.ref_name }} | awk -F'/' '{print $NF}')
          fi
          echo "ref_name=$ref_name" >> $GITHUB_ENV

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.ref_name }}-build
          prerelease: true
          title: Development Build (${{ env.ref_name }})
          files: |
            /tmp/ucm/**/ucm-*.tar.gz
            /tmp/ucm/**/ucm-*.zip
